/**
 * Xiaohongshu (小红书) L3 adapter — Vue SSR state extraction + comment API interception.
 *
 * XHS is a Vue 3 SSR app. All data lives in window.__INITIAL_STATE__ after page load.
 * Direct API calls fail (500) because XHS requires anti-bot signature headers (X-s, X-t, X-s-common)
 * generated by obfuscated JS. Instead we navigate to the right page and read Vue SSR state.
 *
 * Comments are loaded async by the page's own JS — we intercept the API response.
 */
import type { CodeAdapter } from '../../../types/adapter.js'
import type { Page } from 'playwright-core'
import { OpenWebError, toOpenWebError } from '../../../lib/errors.js'

const BASE = 'https://www.xiaohongshu.com'

/* ---------- helpers ---------- */

function asRecord(val: unknown): Record<string, unknown> {
  return (val && typeof val === 'object' ? val : {}) as Record<string, unknown>
}

/* ---------- operation handlers ---------- */

async function searchNotes(page: Page, params: Record<string, unknown>): Promise<unknown> {
  const keyword = String(params.keyword ?? params.query ?? '')
  if (!keyword) throw OpenWebError.missingParam('keyword')

  await page.goto(
    `${BASE}/search_result?keyword=${encodeURIComponent(keyword)}&source=web_search_result_notes`,
    { waitUntil: 'domcontentloaded', timeout: 30000 },
  )
  await page.waitForTimeout(4000)

  return page.evaluate(() => {
    const state = (window as any).__INITIAL_STATE__
    if (!state?.search) return { notes: [], count: 0 }

    const feedsRef = state.search.feeds
    const feeds: any[] = feedsRef?._rawValue ?? feedsRef ?? []
    if (!Array.isArray(feeds)) return { notes: [], count: 0 }

    const notes = feeds
      .filter((f: any) => f.modelType === 'note' && f.noteCard)
      .map((f: any) => {
        const card = f.noteCard
        return {
          noteId: f.id,
          xsecToken: f.xsecToken,
          type: card.type,
          displayTitle: card.displayTitle,
          user: card.user
            ? { userId: card.user.userId, nickname: card.user.nickname, avatar: card.user.avatar }
            : null,
          likedCount: card.interactInfo?.likedCount ?? null,
          cover: card.cover
            ? { url: card.cover.urlDefault, width: card.cover.width, height: card.cover.height }
            : null,
        }
      })

    return { notes, count: notes.length }
  })
}

async function getNoteDetail(page: Page, params: Record<string, unknown>): Promise<unknown> {
  const noteId = String(params.noteId ?? params.note_id ?? '')
  if (!noteId) throw OpenWebError.missingParam('noteId')
  const xsecToken = String(params.xsecToken ?? params.xsec_token ?? '')

  // Intercept comment API response
  const commentPromise = page.waitForResponse(
    (resp) => resp.url().includes('/api/sns/web/v2/comment/page') && resp.status() === 200,
    { timeout: 15000 },
  ).catch(() => null) // intentional: comment API may not fire within timeout

  const tokenParam = xsecToken ? `&xsec_token=${encodeURIComponent(xsecToken)}` : ''
  await page.goto(
    `${BASE}/explore/${noteId}?xsec_source=pc_search${tokenParam}`,
    { waitUntil: 'domcontentloaded', timeout: 30000 },
  )
  await page.waitForTimeout(4000)

  // Extract note from SSR state — map entry is { note, comments, currentTime }
  const noteData = await page.evaluate((id: string) => {
    const state = (window as any).__INITIAL_STATE__
    if (!state?.note) return null

    const mapRef = state.note.noteDetailMap
    const map: Record<string, any> = mapRef?._rawValue ?? mapRef ?? {}
    const entry = map[id]
    if (!entry) return null

    // Data is nested under .note when SSR-hydrated directly
    const detail = entry.note ?? entry

    return {
      noteId: detail.noteId,
      title: detail.title,
      desc: detail.desc,
      type: detail.type,
      time: detail.time,
      lastUpdateTime: detail.lastUpdateTime,
      user: detail.user
        ? { userId: detail.user.userId, nickname: detail.user.nickname, avatar: detail.user.avatar }
        : null,
      interactInfo: detail.interactInfo
        ? {
            likedCount: detail.interactInfo.likedCount,
            collectedCount: detail.interactInfo.collectedCount,
            commentCount: detail.interactInfo.commentCount,
            shareCount: detail.interactInfo.shareCount,
          }
        : null,
      tagList: Array.isArray(detail.tagList)
        ? detail.tagList.map((t: any) => ({ id: t.id, name: t.name, type: t.type }))
        : [],
      imageCount: detail.imageList?.length ?? 0,
    }
  }, noteId)

  // Parse comment response
  let comments: unknown[] = []
  const commentResp = await commentPromise
  if (commentResp) {
    try {
      const json = (await commentResp.json()) as Record<string, unknown>
      const data = asRecord(json.data)
      const rawComments = data.comments as Array<Record<string, unknown>> | undefined
      if (Array.isArray(rawComments)) {
        comments = rawComments.slice(0, 20).map((c) => ({
          id: c.id,
          content: c.content,
          likeCount: c.like_count,
          createTime: c.create_time,
          ipLocation: c.ip_location,
          subCommentCount: c.sub_comment_count,
          user: c.user_info
            ? {
                userId: (c.user_info as Record<string, unknown>).user_id,
                nickname: (c.user_info as Record<string, unknown>).nickname,
                avatar: (c.user_info as Record<string, unknown>).image,
              }
            : null,
        }))
      }
    } catch { /* intentional: comment parse failed — return note without comments */ }
  }

  return { note: noteData, comments }
}

async function getUserProfile(page: Page, params: Record<string, unknown>): Promise<unknown> {
  const userId = String(params.userId ?? params.user_id ?? '')
  if (!userId) throw OpenWebError.missingParam('userId')

  await page.goto(`${BASE}/user/profile/${userId}`, { waitUntil: 'domcontentloaded', timeout: 30000 })

  // Check for CAPTCHA redirect
  if (page.url().includes('captcha') || page.url().includes('login')) {
    throw OpenWebError.apiError('Xiaohongshu', 'CAPTCHA triggered — please solve it in the browser and retry')
  }

  await page.waitForTimeout(4000)

  return page.evaluate(() => {
    const state = (window as any).__INITIAL_STATE__
    if (!state?.user) return null

    const pageDataRef = state.user.userPageData
    const pageData: Record<string, any> = pageDataRef?._rawValue ?? pageDataRef ?? {}

    const basicInfo = pageData.basicInfo?._rawValue ?? pageData.basicInfo ?? {}
    const interactions = pageData.interactions?._rawValue ?? pageData.interactions ?? []
    const tags = pageData.tags?._rawValue ?? pageData.tags ?? []

    return {
      userId: basicInfo.redId ?? null,
      nickname: basicInfo.nickname ?? null,
      desc: basicInfo.desc ?? null,
      gender: basicInfo.gender ?? null,
      avatar: basicInfo.images ?? null,
      avatarLarge: basicInfo.imageb ?? null,
      ipLocation: basicInfo.ipLocation ?? null,
      interactions: Array.isArray(interactions)
        ? interactions.map((i: any) => ({ type: i.type, name: i.name, count: i.count }))
        : [],
      tags: Array.isArray(tags)
        ? tags.map((t: any) => ({ name: t.name, tagType: t.tagType }))
        : [],
    }
  })
}

async function getUserNotes(page: Page, params: Record<string, unknown>): Promise<unknown> {
  const userId = String(params.userId ?? params.user_id ?? '')
  if (!userId) throw OpenWebError.missingParam('userId')

  await page.goto(`${BASE}/user/profile/${userId}`, { waitUntil: 'domcontentloaded', timeout: 30000 })

  if (page.url().includes('captcha') || page.url().includes('login')) {
    throw OpenWebError.apiError('Xiaohongshu', 'CAPTCHA triggered — please solve it in the browser and retry')
  }

  await page.waitForTimeout(4000)

  return page.evaluate(() => {
    const state = (window as any).__INITIAL_STATE__
    if (!state?.user) return { notes: [], count: 0 }

    const notesRef = state.user.notes
    const notePages: any[] = notesRef?._rawValue ?? notesRef ?? []
    if (!Array.isArray(notePages) || notePages.length === 0) return { notes: [], count: 0 }

    // Flatten all pages of notes
    const allNotes: any[] = []
    for (const page of notePages) {
      const items: any[] = page?._rawValue ?? page ?? []
      if (Array.isArray(items)) {
        for (const item of items) {
          if (item?.noteCard) {
            const card = item.noteCard
            allNotes.push({
              noteId: item.id,
              xsecToken: item.xsecToken,
              type: card.type,
              displayTitle: card.displayTitle,
              user: card.user
                ? { userId: card.user.userId, nickname: card.user.nickname, avatar: card.user.avatar }
                : null,
              likedCount: card.interactInfo?.likedCount ?? null,
              cover: card.cover
                ? { url: card.cover.urlDefault, width: card.cover.width, height: card.cover.height }
                : null,
            })
          }
        }
      }
    }

    return { notes: allNotes, count: allNotes.length }
  })
}

async function getExploreFeed(page: Page, _params: Record<string, unknown>): Promise<unknown> {
  await page.goto(`${BASE}/explore`, { waitUntil: 'domcontentloaded', timeout: 30000 })
  await page.waitForTimeout(4000)

  return page.evaluate(() => {
    const state = (window as any).__INITIAL_STATE__
    if (!state?.feed) return { notes: [], count: 0 }

    const feedsRef = state.feed.feeds
    const feeds: any[] = feedsRef?._rawValue ?? feedsRef ?? []
    if (!Array.isArray(feeds)) return { notes: [], count: 0 }

    const notes = feeds
      .filter((f: any) => f.modelType === 'note' && f.noteCard)
      .map((f: any) => {
        const card = f.noteCard
        return {
          noteId: f.id,
          xsecToken: f.xsecToken,
          type: card.type,
          displayTitle: card.displayTitle,
          user: card.user
            ? { userId: card.user.userId, nickname: card.user.nickname, avatar: card.user.avatar }
            : null,
          likedCount: card.interactInfo?.likedCount ?? null,
          cover: card.cover
            ? { url: card.cover.urlDefault, width: card.cover.width, height: card.cover.height }
            : null,
        }
      })

    return { notes, count: notes.length }
  })
}

async function navigateToNote(page: Page, params: Record<string, unknown>): Promise<string> {
  const noteId = String(params.noteId ?? params.note_id ?? '')
  if (!noteId) throw OpenWebError.missingParam('noteId')
  const xsecToken = String(params.xsecToken ?? params.xsec_token ?? '')

  const tokenParam = xsecToken ? `&xsec_token=${encodeURIComponent(xsecToken)}` : ''
  await page.goto(
    `${BASE}/explore/${noteId}?xsec_source=pc_search${tokenParam}`,
    { waitUntil: 'domcontentloaded', timeout: 30000 },
  )
  await page.waitForTimeout(4000)
  return noteId
}

async function likeNote(page: Page, params: Record<string, unknown>): Promise<unknown> {
  const noteId = await navigateToNote(page, params)

  // Check current liked state
  const wasLiked = await page.evaluate(() => {
    const state = (window as any).__INITIAL_STATE__
    const mapRef = state?.note?.noteDetailMap
    const map: Record<string, any> = mapRef?._rawValue ?? mapRef ?? {}
    const entry = Object.values(map)[0] as any
    return (entry?.note ?? entry)?.interactInfo?.liked ?? false
  })

  if (wasLiked) return { noteId, liked: true, action: 'already_liked' }

  // Intercept the like API response
  const likePromise = page.waitForResponse(
    (resp) => resp.url().includes('/api/sns/web/v1/note/like') && resp.status() === 200,
    { timeout: 10000 },
  ).catch(() => null)

  await page.click('.engage-bar-style .like-wrapper', { timeout: 5000 })
  const likeResp = await likePromise

  const success = !!likeResp
  return { noteId, liked: success, action: success ? 'liked' : 'failed' }
}

async function bookmarkNote(page: Page, params: Record<string, unknown>): Promise<unknown> {
  const noteId = await navigateToNote(page, params)

  // Check current collected state
  const wasCollected = await page.evaluate(() => {
    const state = (window as any).__INITIAL_STATE__
    const mapRef = state?.note?.noteDetailMap
    const map: Record<string, any> = mapRef?._rawValue ?? mapRef ?? {}
    const entry = Object.values(map)[0] as any
    return (entry?.note ?? entry)?.interactInfo?.collected ?? false
  })

  if (wasCollected) return { noteId, bookmarked: true, action: 'already_bookmarked' }

  // Intercept the collect API response
  const collectPromise = page.waitForResponse(
    (resp) => resp.url().includes('/api/sns/web/v1/note/collect') && resp.status() === 200,
    { timeout: 10000 },
  ).catch(() => null)

  await page.click('.engage-bar-style .collect-wrapper', { timeout: 5000 })
  const collectResp = await collectPromise

  const success = !!collectResp
  return { noteId, bookmarked: success, action: success ? 'bookmarked' : 'failed' }
}

/* ---------- adapter export ---------- */

const OPERATIONS: Record<string, (page: Page, params: Record<string, unknown>) => Promise<unknown>> = {
  searchNotes,
  getNoteDetail,
  getUserProfile,
  getUserNotes,
  getExploreFeed,
  likeNote,
  bookmarkNote,
}

const adapter: CodeAdapter = {
  name: 'xiaohongshu-web',
  description: 'Xiaohongshu (小红书) — search, detail, profile, user notes, explore feed, like, bookmark via Vue SSR + button interaction',

  async init(page: Page): Promise<boolean> {
    const url = page.url()
    return url.includes('xiaohongshu.com')
  },

  async isAuthenticated(page: Page): Promise<boolean> {
    const cookies = await page.context().cookies('https://www.xiaohongshu.com')
    return cookies.some((c) => c.name === 'web_session')
  },

  async execute(page: Page, operation: string, params: Readonly<Record<string, unknown>>): Promise<unknown> {
    try {
      const handler = OPERATIONS[operation]
      if (!handler) throw OpenWebError.unknownOp(operation)
      return handler(page, { ...params })
    } catch (error) {
      throw toOpenWebError(error)
    }
  },
}

export default adapter
