/**
 * JD Global L3 adapter — h5st-signed API calls via page.evaluate().
 *
 * JD Global (global.jd.com) uses api.m.jd.com with h5st anti-bot signing
 * generated by the PSign library loaded in the page's JavaScript context.
 * All API calls must go through page.evaluate() to use the signing mechanism.
 *
 * Operations:
 *   getRecommendations     — homepage product recommendations (37 products)
 *   getPromoBanners        — promotional banner ads
 *   getSquarePromotions    — square promotional modules
 *   getNewsMessages        — site news/announcements
 *   getCategoryNavigation  — category tree from DOM
 */
import type { CodeAdapter } from "../../../types/adapter.js";
import type { Page } from "playwright";

const JD_GLOBAL = "https://global.jd.com";

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

async function ensureJdPage(page: Page): Promise<void> {
	if (!page.url().includes("global.jd.com")) {
		await page.evaluate((url: string) => {
			window.location.href = url;
		}, JD_GLOBAL);
		await sleep(5000);
		await page
			.waitForLoadState("networkidle", { timeout: 10000 })
			.catch(() => {});
	}
}

/**
 * Call api.m.jd.com with PSign h5st signing from browser context.
 */
async function signedApiCall(
	page: Page,
	functionId: string,
	body: Record<string, unknown>,
): Promise<unknown> {
	return page.evaluate(
		async ({
			functionId,
			bodyStr,
		}: { functionId: string; bodyStr: string }) => {
			const t = String(Date.now());

			// Use PSign to generate h5st signature
			const PSign = (window as unknown as { PSign: { sign: (p: Record<string, string>) => Promise<Record<string, string>> } }).PSign;
			if (!PSign?.sign)
				throw new Error("PSign not available — page not ready");

			const signed = await PSign.sign({
				functionId,
				body: bodyStr,
				appid: "oversea_pc",
				client: "wh5",
				t,
			});

			const params = new URLSearchParams(
				signed as unknown as Record<string, string>,
			);
			const res = await fetch(
				`https://api.m.jd.com/?${params.toString()}`,
				{ credentials: "include" },
			);
			return res.json();
		},
		{ functionId, bodyStr: JSON.stringify(body) },
	);
}

async function queryModule(
	page: Page,
	moduleType: string,
	moduleId: string,
	moduleName: string,
): Promise<unknown> {
	const body = {
		stage: 0,
		commentType: "",
		sourceCode: "pcDt",
		pageId: "",
		qryParam: JSON.stringify([
			{ type: moduleType, mapTo: moduleName, id: moduleId },
		]),
		applyKey: moduleName,
	};

	const result = (await signedApiCall(
		page,
		"qryCompositeMaterials",
		body,
	)) as {
		code: string;
		data: Record<string, unknown>;
	};
	if (result.code !== "0") throw new Error(`API error: ${result.code}`);
	return result.data?.[moduleName];
}

/* ---------- Operations ---------- */

interface JdProduct {
	skuId: string;
	name: string;
	jdPrice: string;
	pcpPrice: string;
	pPrice: string;
	shopId: number;
	shopName: string;
	commentCount: number;
	goodRate: string;
	image: string;
	classIdL1: string;
	classIdL2: string;
	classIdL3: string;
	brandId: string;
}

async function getRecommendations(
	page: Page,
	_params: Record<string, unknown>,
): Promise<unknown> {
	await ensureJdPage(page);
	await sleep(2000);

	const data = (await queryModule(
		page,
		"productGroup",
		"12240015",
		"recommend",
	)) as { list: JdProduct[]; groupName: string };
	if (!data?.list) throw new Error("No recommendation data returned");

	return {
		title: data.groupName || "为你推荐",
		count: data.list.length,
		products: data.list.map((p: JdProduct) => ({
			skuId: p.skuId,
			name: p.name,
			jdPrice: p.jdPrice,
			originalPrice: p.pcpPrice,
			promotionalPrice: p.pPrice,
			shopId: p.shopId,
			shopName: p.shopName,
			commentCount: p.commentCount,
			goodRate: p.goodRate,
			image: p.image ? `https:${p.image}` : null,
			categoryL1: p.classIdL1,
			categoryL2: p.classIdL2,
			categoryL3: p.classIdL3,
			brandId: p.brandId,
		})),
	};
}

interface JdBanner {
	advertId: string;
	name: string;
	pictureUrl: string;
	link: string;
	desc: string;
}

async function getPromoBanners(
	page: Page,
	_params: Record<string, unknown>,
): Promise<unknown> {
	await ensureJdPage(page);
	await sleep(2000);

	const data = (await queryModule(
		page,
		"advertGroup",
		"05382124",
		"banners",
	)) as { list: JdBanner[]; groupName: string };
	if (!data?.list) throw new Error("No banner data returned");

	return {
		title: data.groupName || "首焦",
		banners: data.list.map((b: JdBanner) => ({
			id: b.advertId,
			name: b.name,
			image: b.pictureUrl ? `https:${b.pictureUrl}` : null,
			link: b.link,
			description: b.desc,
		})),
	};
}

async function getSquarePromotions(
	page: Page,
	_params: Record<string, unknown>,
): Promise<unknown> {
	await ensureJdPage(page);
	await sleep(2000);

	// Fetch both square modules
	const [left, right] = await Promise.all([
		queryModule(
			page,
			"advertGroup",
			"06813315",
			"squareLeft",
		) as Promise<{ list: JdBanner[]; groupName: string }>,
		queryModule(
			page,
			"advertGroup",
			"06813381",
			"squareRight",
		) as Promise<{ list: JdBanner[]; groupName: string }>,
	]);

	const mapBanners = (list: JdBanner[]) =>
		(list || []).map((b) => ({
			id: b.advertId,
			name: b.name,
			image: b.pictureUrl ? `https:${b.pictureUrl}` : null,
			link: b.link,
		}));

	return {
		left: {
			title: left?.groupName || "会场模块",
			items: mapBanners(left?.list),
		},
		right: {
			title: right?.groupName || "会场模块小",
			items: mapBanners(right?.list),
		},
	};
}

async function getNewsMessages(
	page: Page,
	_params: Record<string, unknown>,
): Promise<unknown> {
	await ensureJdPage(page);
	await sleep(2000);

	const data = (await queryModule(
		page,
		"advertGroup",
		"06784803",
		"messages",
	)) as { list: JdBanner[]; groupName: string };
	if (!data?.list) throw new Error("No message data returned");

	return {
		title: data.groupName || "全球特讯",
		messages: data.list.map((m: JdBanner) => ({
			id: m.advertId,
			title: m.name,
			link: m.link,
			description: m.desc,
		})),
	};
}

async function getCategoryNavigation(
	page: Page,
	_params: Record<string, unknown>,
): Promise<unknown> {
	await ensureJdPage(page);
	await sleep(2000);

	return page.evaluate(() => {
		// Extract category navigation from the sidebar (floor 1)
		const categoryFloor = document.querySelectorAll(".floor")[1];
		if (!categoryFloor) return { categories: [] };

		const allLinks = categoryFloor.querySelectorAll("a[href]");
		const categories: { name: string; url: string }[] = [];
		const seen = new Set<string>();

		for (const link of allLinks) {
			const a = link as HTMLAnchorElement;
			const name = a.textContent?.trim();
			if (
				name &&
				name.length > 0 &&
				name.length < 20 &&
				!seen.has(name) &&
				!name.includes("登录") &&
				!name.includes("注册") &&
				!name.includes("福利") &&
				!name.includes("切换") &&
				!name.includes("退出") &&
				!name.includes("PLUS") &&
				!name.includes("更多") &&
				!name.includes("物流") &&
				!name.includes("客户") &&
				!name.includes("售后") &&
				!a.href.includes("passport") &&
				!a.href.includes("home.jd.com") &&
				!a.href.includes("vip.jd.com") &&
				!a.href.includes("plus.jd.com") &&
				!a.href.includes("help.jd.com") &&
				!a.href.includes("jdcs.jd.com") &&
				!a.href.includes("phat.jd.com")
			) {
				seen.add(name);
				categories.push({ name, url: a.href });
			}
		}

		return { categories };
	});
}

const OPERATIONS: Record<
	string,
	(page: Page, params: Record<string, unknown>) => Promise<unknown>
> = {
	getRecommendations,
	getPromoBanners,
	getSquarePromotions,
	getNewsMessages,
	getCategoryNavigation,
};

const adapter: CodeAdapter = {
	name: "jd-global-api",
	description:
		"JD Global — product recommendations, promotional content, and categories via h5st-signed API",

	async init(page: Page): Promise<boolean> {
		return page.url().includes("global.jd.com");
	},

	async isAuthenticated(): Promise<boolean> {
		return true; // Public data doesn't require auth
	},

	async execute(
		page: Page,
		operation: string,
		params: Readonly<Record<string, unknown>>,
	): Promise<unknown> {
		const handler = OPERATIONS[operation];
		if (!handler) throw new Error(`Unknown operation: ${operation}`);
		return handler(page, { ...params });
	},
};

export default adapter;
